export const LOADING_CATEGORY = 'LOADING_CATEGORY';
export const LOAD_CATEGORY_SUCCESS = 'LOAD_CATEGORY_SUCCESS';
export const LOAD_CATEGORY_FAILURE = 'LOAD_CATEGORY_FAILURE';

export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SET_SEARCH_INDEX_RESULT = 'SET_SEARCH_INDEX_RESULT';

export const SET_AUTH_FIELD = 'SET_AUTH_FIELD';
export const TOGGLE_AUTH_FIELDS = 'TOGGLE_AUTH_FIELDS';

export const SET_REGISTER_FORM_FIELD = 'SET_REGISTER_FORM_FIELD';
export const SET_LOGIN_FORM_FIELD = 'SET_LOGIN_FORM_FIELD';

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SUCCESSFUL_LOGIN = 'SUCCESSFUL_LOGIN';
export const FAILED_LOGIN = 'FAILED_LOGIN';

export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const SUCCESSFUL_REGISTRATION = 'SUCCESSFUL_REGISTRATION';
export const FAILED_REGISTRATION = 'FAILED_REGISTRATION';

export const LOGOUT = 'LOGOUT';

export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';

export const ADD_INSTRUCTION = 'ADD_INSTRUCTION';
export const REMOVE_INSTRUCTION = 'REMOVE_INSTRUCTION';

export const OPEN_ADD_CATEGORY_MODAL = 'OPEN_ADD_CATEGORY_MODAL'
export const OPEN_EDIT_CATEGORY_MODAL = 'OPEN_EDIT_CATEGORY_MODAL'

export const CLOSE_CATEGORY_MODAL = 'CLOSE_CATEGORY_MODAL';

export const ADD_NEW_CATEGORY_SUCCESSFUL = 'ADD_NEW_CATEGORY_SUCCESSFUL';
export const ADD_NEW_CATEGORY_FAILURE = 'ADD_NEW_CATEGORY_FAILURE';

export const EDIT_CATEGORY_SUCCESSFUL = 'EDIT_CATEGORY_SUCCESSFUL';
export const EDIT_CATEGORY_FAILURE = 'EDIT_CATEGORY_FAILURE';

export const SET_INSTRUCTION_FIELD = 'SET_INSTRUCTION_FIELD';
export const SET_CATEGORY_TITLE_FIELD = 'SET_CATEGORY_TITLE_FIELD';
