export const LOADING_CATEGORY = 'LOADING_CATEGORY';
export const LOAD_CATEGORY_SUCCESS = 'LOAD_CATEGORY_SUCCESS';
export const LOAD_CATEGORY_FAILURE = 'LOAD_CATEGORY_FAILURE';

export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SET_SEARCH_INDEX_RESULT = 'SET_SEARCH_INDEX_RESULT';

export const SET_AUTH_FIELD = 'SET_AUTH_FIELD';
export const TOGGLE_AUTH_FIELDS = 'TOGGLE_AUTH_FIELDS';

export const SET_REGISTER_FORM_FIELD = 'SET_REGISTER_FORM_FIELD';
export const SET_LOGIN_FORM_FIELD = 'SET_LOGIN_FORM_FIELD';

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SUCCESSFUL_LOGIN = 'SUCCESSFUL_LOGIN';
export const FAILED_LOGIN = 'FAILED_LOGIN';

export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const SUCCESSFUL_REGISTRATION = 'SUCCESSFUL_REGISTRATION';
export const FAILED_REGISTRATION = 'FAILED_REGISTRATION';
