export const LOADING_CATEGORY = 'LOADING_CATEGORY';
export const LOAD_CATEGORY_SUCCESS = 'LOAD_CATEGORY_SUCCESS';
export const LOAD_CATEGORY_FAILURE = 'LOAD_CATEGORY_FAILURE';

export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SET_SEARCH_INDEX_RESULT = 'SET_SEARCH_INDEX_RESULT';
